### ISSUE TITLE
Calls reflecting Self Buffs applied at Quest Start should be excluded from view

### ISSUE THREAD

**Issue by inkwelder** [dissidiadb/v2#9]
Calls that trigger a self buff, even if there is an aura attached, should be removed from view, as no party member can take advantage of the aura. Debuffs are very relevant, as well as party buffs (i.e. Rydia base call).

Test with Arciela Descension buff, which has an 80% party ATK attached. This should not be shown when related specifically to the call.

**Comment by remsk** [comment]
Fixed by removing status effects granted to self with CAs

**Comment by remsk** [comment]
Fixed by removing status effects granted to self with CAs
